=== eomjinyoung/Java46/web01t/step07/WebContent/xml/step2/books.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT books   (book*)>
<!ELEMENT book    (title,press,page,price,(in|out)?,author+)>
<!ELEMENT title   (#PCDATA)>
<!ELEMENT press   (#PCDATA)>
<!ELEMENT page    (#PCDATA)>
<!ELEMENT price   (#PCDATA)>
<!ELEMENT in      EMPTY>
<!ELEMENT out     EMPTY>
<!ELEMENT author  (#PCDATA)>

<!ATTLIST books
  version     CDATA     #FIXED "1.0">

<!ATTLIST book
  hardcover   (yes|no)  "no"
  isbn        ID        #REQUIRED>
  
<!ATTLIST author
  no          ID        #REQUIRED
  email       CDATA     #REQUIRED
  tel         CDATA     #IMPLIED>

=== eomjinyoung/Java46/web01t/step14/WebContent/xml/step2/book01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books SYSTEM "books.dtd">
<books version="1.0">
  <book hardcover="yes" isbn="B001">
    <title></title>
    <press></press>
    <page></page>
    <price></price>
    <in/>
    <author no="A001" email="heo@test.com">허균</author>
  </book>
  <book isbn="B002">
    <title></title>
    <press></press>
    <page></page>
    <price></price>
    <author no="A002" email="oh@test.com" tel="111-2222">오호라</author>
    <author no="A003" email="pu@test.com">푸하하</author>
  </book>
</books>
